# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user1 = Fabricate(:user, name: "Joe Smith")
user2 = Fabricate(:user, name: "John Adams")
user3 = Fabricate(:user, name: "Ben Franklin")
user4 = Fabricate(:user, name: "Gouvernor Morris")
user5 = Fabricate(:user, name: "Sam Adams")
user6 = Fabricate(:user, name: "John Hancock")
user7 = Fabricate(:user, name: "Patrick Henry")
user8 = Fabricate(:user, name: "Henry Clay")

course1 = Fabricate(:course,
          user_id: user1.id,
          name: "Designing Cities",
          url: "https://www.coursera.org/course/designingcities",
          description: "Designing Cities is a ten-week course starting in September 2014.  Every week will focus on a different aspect of Designing Cities including: How Today’s City Evolved; The Ideas That Shape Cities; Tools for Designing Cities; Making Cities Sustainable; Cities in the Information Age; Preserving Older Cities; Designing New Cities, Districts and Neighborhoods; The Challenges of Informal Cities and Disadvantaged Neighborhoods; and Visionary Cities.  Materials will be presented by the instructors and guest faculty from PennDesign through a series of five or more modules per week, each typically 10-12 minutes long. The first module each week will be a roundtable discussion among professors Stefan Al, Jonathan Barnett, and Gary Hack introducing the big issues associated with the subject.  Each succeeding module will be a self-contained illustrated presentation of a set of ideas and images. There will be a list of suggested readings for those who wish to follow up on the ideas in each module.  Everyone enrolled in Designing Cities will be expected to complete 3 assignments.  These will be posted on the course site and they will be in the form of peer assessments. There will also be three sessions where we discuss a selection of the assignments that have been submitted. There will be a great deal to be learned from the ideas participants submit, reflecting cities of all sizes and circumstances across the globe.  The course concludes with a discussion by the faculty of the issues raised in the discussion groups and responses to the assignments. We are looking forward to connecting with you and seeing the issues at the forefront in designing your city.",
          date: "2014-09-14",
          cost: 0,
          instructor: "Gary Hack",
          institution: "University of Pennsylvania",
          duration: "10 weeks",
          level: "Beginner",
          tags: "geography, design, engineering, cities")

course2 = Fabricate(:course,
          user_id: user2.id,
          name: "Computational Investing 1",
          url: "https://www.coursera.org/course/compinvesting1",
          description: "Why do the prices of some companies’ stocks seem to move up and down together while others move separately? What does portfolio “diversification” really mean and how important is it? What should the price of a stock be? How can we discover and exploit the relationships between equity prices automatically? We’ll examine these questions, and others, from a computational point of view. You will learn many of the principles and algorithms hedge funds and investment professionals use to maximize return and reduce risk in equity portfolios.",
          date: "2014-09-12",
          cost: 0,
          instructor: "Tucker Balch",
          institution: "Georgia Institute of Technology",
          duration: "8 weeks",
          level: "Intermediate",
          tags: "programming, finance, investing, math, econometrics")

course3 = Fabricate(:course,
          user_id: user3.id,
          name: "An Introduction to Interactive Programming in Python",
          url: "https://www.coursera.org/course/interactivepython",
          description: "This course is designed to help students with very little or no computing background learn the basics of building simple interactive applications.  Our language of choice, Python, is an easy-to learn, high-level computer language that is used in many of the computational courses offered on Coursera. To make learning Python easy, we have developed a new browser-based programming environment that makes developing interactive applications in Python simple.  These applications will involve windows whose contents are graphical and respond to buttons, the keyboard and the mouse. The primary method for learning the course material will be to work through multiple mini-projects in Python.  To make this class enjoyable, these projects will include building fun games such as Pong, Blackjack, and Asteroids.  When you’ve finished our course, we can’t promise that you will be a professional programmer, but we think that you will learn a lot about programming in Python and have fun while you’re doing it.",
          date: "2014-09-15",
          cost: 0,
          instructor: "Joe Warren",
          institution: "Rice University",
          duration: "9 weeks",
          level: "Beginner",
          tags: "programming, python, math, computing")

course4 = Fabricate(:course,
          user_id: user4.id,
          name: "Supply Chain and Logistics Fundamentals",
          url: "https://www.edx.org/course/mitx/mitx-ctl-sc1x-supply-chain-logistics-2006#.VCS6FCldXM0",
          description: "Companies worldwide are leveraging supply chain management to create and maintain a strategic competitive advantage. This trend, in turn, is fueling a growing demand for supply chain professionals. This course is the first of three in the Supply Chain Management XSeries that is specifically designed to teach the critical skills needed to be successful in this exciting field.  This first course, CTL.SC1x, provides the foundational skills for supply chain management and logistics. You will learn how to develop and apply analytic tools, approaches, and techniques used in the design and operation of logistics systems and integrated supply chains. The material is taught from a managerial perspective, with an emphasis on where and how specific tools can be used to improve the overall performance and reduce the total cost of a supply chain. We place a strong emphasis on the development and use of fundamental models to illustrate the underlying concepts involved in both intra- and inter-company logistics operations.",
          date: "2014-09-30",
          cost: 0,
          instructor: "Chris Caplice",
          institution: "MIT",
          duration: "11 weeks",
          level: "Intermediate",
          tags: "probability, calculus, statistics, logistics, supply chain")

course5 = Fabricate(:course,
          user_id: user5.id,
          name: "Fantasy and Science Fiction: The Human Mind, Our Modern World",
          url: "https://www.coursera.org/course/fantasysf",
          description: "Fantasy is a key term both in psychology and in the art and artifice of humanity. The things we make, including our stories, reflect, serve, and often shape our needs and desires. We see this everywhere from fairy tale to kiddie lit to myth; from 'Cinderella' to Alice in Wonderland to Superman; from building a fort as a child to building ideal, planned cities as whole societies. Fantasy in ways both entertaining and practical serves our persistent needs and desires and illuminates the human mind. Fantasy expresses itself in many ways, from the comfort we feel in the godlike powers of a fairy godmother to the seductive unease we feel confronting Dracula. From a practical viewpoint, of all the fictional forms that fantasy takes, science fiction, from Frankenstein to Avatar, is the most important in our modern world because it is the only kind that explicitly recognizes the profound ways in which science and technology, those key products of the human mind, shape not only our world but our very hopes and fears. This course will explore Fantasy in general and Science Fiction in specific both as art and as insights into ourselves and our world.",
          date: "2014-10-06",
          cost: 0,
          instructor: "Eric Rabkin",
          institution: "University of Michigan",
          duration: "11 weeks",
          level: "Beginner",
          tags: "science fiction, fantasy, english, writing, reading, reading comprehension")

course6 = Fabricate(:course,
          user_id: user6.id,
          name: "Intro to HTML and CSS",
          url: "https://www.udacity.com/course/ud304",
          description: "HTML and CSS are markup languages and the building blocks that make up the web. This course will teach you how to use them, but also much more than that. It is called 'Not your Typical Intro...' because it does not follow the usual pattern of other courses and tutorials that you find on the Internet. Usually HTML and CSS is taught with a focus on language syntax. But knowing syntax alone does not enable you to create a webpage from a design. You need to know where to start and how to approach the task, in other words - you need to learn how to think like a front-end developer. In this course you will learn how to convert digital design mockups into static web pages. We will teach you how to approach page layout, how to break down a design mockup into page elements, and how to implement that in HTML and CSS.  You will also learn about responsive design techniques, which are increasingly important in a world where mobile devices and TV screens are used more and more often to look for information and entertainment.",
          date: "2014-09-30",
          cost: 150,
          instructor: "Cameron Pittman",
          institution: "Udacity",
          duration: "3 weeks",
          level: "Beginner",
          tags: "html, css, design, web development, programming, front end")

course7 = Fabricate(:course,
          user_id: user7.id,
          name: "Introduction to Philosophy: God, Knowledge and Consciousness",
          url: "https://www.edx.org/course/mitx/mitx-24-00x-introduction-philosophy-god-2481#.VCTACyldXM0",
          description: "This course has two goals. The first is to introduce you to the things that philosophers think about. We will look at some perennial philosophical problems: Is there a God? What is knowledge, and how do we get it? What is the place of our consciousness in the physical world? Do we have free will? How do we persist over time, as our bodily and psychological traits change? The second goal is to get you thinking philosophically yourself. This will help you develop your critical reasoning and argumentative skills more generally. Along the way we will draw from late, great classical authors and influential contemporary figures. If you wish to take the course as a 'verified' student (technological checks guarantee it is you taking the course) then please register as Verified below. It will cost you $50. Upon completing the course you will receive a certificate that says that you completed the course as a 'verified' student. Otherwise you can take the course as a non-verified student (you guarantee it is you taking the course by signing an honor code) for free. You will receive a certificate that says that you completed the course as a non-verified student.",
          date: "2014-09-30",
          cost: 0,
          instructor: "Caspar Hare",
          institution: "MIT",
          duration: "12 weeks",
          level: "Beginner",
          tags: "philosophy, ethics, metaphysics, god, religion, atheism, theory of knowledge")

course8 = Fabricate(:course,
          user_id: user8.id,
          name: "Electrify: An Introduction to Electrical and Electronic Engineering",
          url: "https://www.edx.org/course/mitx/mitx-24-00x-introduction-philosophy-god-2481#.VCTACyldXM0",
          description: "Engineering is all about using science to make the world a better place and touches our everyday lives; the device you’re reading this on wouldn’t exist if it wasn’t for electrical and electronic engineers! You won’t find a hard hat or a spanner anywhere in this course, we’ll be focussing on how engineers use their brains to solve problems and to give a taste of some of the topics a degree level course in Electrical and Electronic Engineering may include.",
          date: "2014-09-22",
          cost: 0,
          instructor: "Leah Ridgway",
          institution: "University of Liverpool",
          duration: "6 weeks",
          level: "Beginner",
          tags: "engineering, electrical engineering, math, science, computers, hardware")

course9 = Fabricate(:course,
          user_id: user8.id,
          name: "War for the Greater Middle East",
          url: "https://www.edx.org/course/bux/bux-intl301x-war-greater-middle-east-1556#.VCTB8ildXM0",
          description: "Over thirty years ago, confident in the superiority of American military power, the United States set out to 'fix' the Greater Middle East. Since that time, U.S. troops, covert operatives and proxies have engaged in costly exertions in predominantly Muslim societies everywhere from the Levant and the Persian Gulf to East Africa and Central Asia. With what result? Washington's efforts have exacted a terrible toll, squandering vast amounts of blood and treasure. In the meantime, the Islamic world has become less stable while anti-American radicalism flourishes. America’s War for the Greater Middle East has failed, and that failure is irreversible. This course offers a history of that war. It identifies the factors that inspired the United States to launch the conflict and to persist in a doomed enterprise. It describes how the war unfolded from one phase to the next, from the era of Jimmy Carter to the age of Barack Obama. It catalogs errors of judgment and implementation made along the way. It invites students to consider alternative approaches to policy that might have better served the interests of the United States and of the people living in countries invaded, occupied, bombed and otherwise subjected to American punishment.",
          date: "2014-09-24",
          cost: 0,
          instructor: "Andrew Bacevich",
          institution: "Boston University",
          duration: "7 weeks",
          level: "Beginner",
          tags: "history, conflict, middle east")

course10 = Fabricate(:course,
          user_id: user1.id,
          name: "Waves & Optics",
          url: "https://www.edx.org/course/ricex/ricex-phys201x-waves-optics-3261#.VCTDSSldXM0",
          description: "PHYS201x follows introductory physics courses with a more detailed treatment of oscillators, waves on strings, and electromagnetic waves. In addition to deriving and solving the wave equation, mathematical methods will be introduced on making approximations, describing oscillations with complex numbers, and synthesizing functions with Fourier series. Optical reflection and refraction will be derived, as well as the lens equation and elements of geometrical optics. Optical interference, diffraction, and polarization will be covered in detail, including the role of diffraction in image formation. PHYS201x will have weekly video lectures that explain the material through detailed derivations and demonstrations. There will be weekly homework, a discussion forum, and two exams. Eight weeks of content will be presented, and one week devoted to each self-paced exam.",
          date: "2014-10-06",
          cost: 0,
          instructor: "Jason Hafner",
          institution: "Rice University",
          duration: "11 weeks",
          level: "Intermediate",
          tags: "physics, optics, math, science")

course11 = Fabricate(:course,
          user_id: user2.id,
          name: "Health Literacy and Communication for Health Professionals",
          url: "https://www.coursera.org/course/healthliteracy",
          description: "This inter-professional course will help educate a variety of health professionals about health literacy efforts and improved communication skills. It will require your active participation in creating health literate interactions at various organizational levels. This course will provide the opportunity to reinforce existing opportunities to work together as a multidisciplinary team or fill a gap if you haven’t had an opportunity to do so yet!",
          date: "2014-10-19",
          cost: 0,
          instructor: "Denise H. Britigan",
          institution: "University of Nebraska",
          duration: "8 weeks",
          level: "Beginner",
          tags: "health, wellness, healthcare")

comment1 = Fabricate(:comment, user_id: user1.id, course_id: course1.id, comment_text: "This course is awesome---the professor is excellent!")
comment2 = Fabricate(:comment, user_id: user2.id, course_id: course1.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment3 = Fabricate(:comment, user_id: user3.id, course_id: course1.id, comment_text: "Course went way too fast for me.")
comment4 = Fabricate(:comment, user_id: user4.id, course_id: course1.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment5 = Fabricate(:comment, user_id: user5.id, course_id: course1.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment6 = Fabricate(:comment, user_id: user6.id, course_id: course1.id, comment_text: "What a wonderful learning experience!")
comment7 = Fabricate(:comment, user_id: user7.id, course_id: course1.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment8 = Fabricate(:comment, user_id: user8.id, course_id: course1.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment9 = Fabricate(:comment, user_id: user1.id, course_id: course1.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment10 = Fabricate(:comment, user_id: user1.id, course_id: course2.id, comment_text: "This course is awesome---the professor is excellent!")
comment11 = Fabricate(:comment, user_id: user2.id, course_id: course2.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment12 = Fabricate(:comment, user_id: user3.id, course_id: course2.id, comment_text: "Course went way too fast for me.")
comment13 = Fabricate(:comment, user_id: user4.id, course_id: course2.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment14 = Fabricate(:comment, user_id: user5.id, course_id: course2.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment15 = Fabricate(:comment, user_id: user6.id, course_id: course2.id, comment_text: "What a wonderful learning experience!")
comment16 = Fabricate(:comment, user_id: user7.id, course_id: course2.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment17 = Fabricate(:comment, user_id: user8.id, course_id: course2.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment18 = Fabricate(:comment, user_id: user1.id, course_id: course2.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment19 = Fabricate(:comment, user_id: user1.id, course_id: course3.id, comment_text: "This course is awesome---the professor is excellent!")
comment20 = Fabricate(:comment, user_id: user2.id, course_id: course3.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment21 = Fabricate(:comment, user_id: user3.id, course_id: course3.id, comment_text: "Course went way too fast for me.")
comment22 = Fabricate(:comment, user_id: user4.id, course_id: course3.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment23 = Fabricate(:comment, user_id: user5.id, course_id: course3.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment24 = Fabricate(:comment, user_id: user6.id, course_id: course3.id, comment_text: "What a wonderful learning experience!")
comment25 = Fabricate(:comment, user_id: user7.id, course_id: course3.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment26 = Fabricate(:comment, user_id: user8.id, course_id: course3.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment27 = Fabricate(:comment, user_id: user1.id, course_id: course3.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment28 = Fabricate(:comment, user_id: user1.id, course_id: course4.id, comment_text: "This course is awesome---the professor is excellent!")
comment29 = Fabricate(:comment, user_id: user2.id, course_id: course4.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment30 = Fabricate(:comment, user_id: user3.id, course_id: course4.id, comment_text: "Course went way too fast for me.")
comment31 = Fabricate(:comment, user_id: user4.id, course_id: course4.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment32 = Fabricate(:comment, user_id: user5.id, course_id: course4.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment33 = Fabricate(:comment, user_id: user6.id, course_id: course4.id, comment_text: "What a wonderful learning experience!")
comment34 = Fabricate(:comment, user_id: user7.id, course_id: course4.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment35 = Fabricate(:comment, user_id: user8.id, course_id: course4.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment36 = Fabricate(:comment, user_id: user1.id, course_id: course4.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment37 = Fabricate(:comment, user_id: user1.id, course_id: course5.id, comment_text: "This course is awesome---the professor is excellent!")
comment38 = Fabricate(:comment, user_id: user2.id, course_id: course5.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment39 = Fabricate(:comment, user_id: user3.id, course_id: course5.id, comment_text: "Course went way too fast for me.")
comment40 = Fabricate(:comment, user_id: user4.id, course_id: course5.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment41 = Fabricate(:comment, user_id: user5.id, course_id: course5.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment42 = Fabricate(:comment, user_id: user6.id, course_id: course5.id, comment_text: "What a wonderful learning experience!")
comment43 = Fabricate(:comment, user_id: user7.id, course_id: course5.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment44 = Fabricate(:comment, user_id: user8.id, course_id: course5.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment45 = Fabricate(:comment, user_id: user1.id, course_id: course5.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment46 = Fabricate(:comment, user_id: user1.id, course_id: course6.id, comment_text: "This course is awesome---the professor is excellent!")
comment47 = Fabricate(:comment, user_id: user2.id, course_id: course6.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment48 = Fabricate(:comment, user_id: user3.id, course_id: course6.id, comment_text: "Course went way too fast for me.")
comment49 = Fabricate(:comment, user_id: user4.id, course_id: course6.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment50 = Fabricate(:comment, user_id: user5.id, course_id: course6.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment51 = Fabricate(:comment, user_id: user6.id, course_id: course6.id, comment_text: "What a wonderful learning experience!")
comment52 = Fabricate(:comment, user_id: user7.id, course_id: course6.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment53 = Fabricate(:comment, user_id: user8.id, course_id: course6.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment54 = Fabricate(:comment, user_id: user1.id, course_id: course6.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment55 = Fabricate(:comment, user_id: user1.id, course_id: course7.id, comment_text: "This course is awesome---the professor is excellent!")
comment56 = Fabricate(:comment, user_id: user2.id, course_id: course7.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment57 = Fabricate(:comment, user_id: user3.id, course_id: course7.id, comment_text: "Course went way too fast for me.")
comment58 = Fabricate(:comment, user_id: user4.id, course_id: course7.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment59 = Fabricate(:comment, user_id: user5.id, course_id: course7.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment60 = Fabricate(:comment, user_id: user6.id, course_id: course7.id, comment_text: "What a wonderful learning experience!")
comment61 = Fabricate(:comment, user_id: user7.id, course_id: course7.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment62 = Fabricate(:comment, user_id: user8.id, course_id: course7.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment63 = Fabricate(:comment, user_id: user1.id, course_id: course7.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment64 = Fabricate(:comment, user_id: user1.id, course_id: course8.id, comment_text: "This course is awesome---the professor is excellent!")
comment65 = Fabricate(:comment, user_id: user2.id, course_id: course8.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment66 = Fabricate(:comment, user_id: user3.id, course_id: course8.id, comment_text: "Course went way too fast for me.")
comment67 = Fabricate(:comment, user_id: user4.id, course_id: course8.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment68 = Fabricate(:comment, user_id: user5.id, course_id: course8.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment69 = Fabricate(:comment, user_id: user6.id, course_id: course8.id, comment_text: "What a wonderful learning experience!")
comment70 = Fabricate(:comment, user_id: user7.id, course_id: course8.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment71 = Fabricate(:comment, user_id: user8.id, course_id: course8.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment72 = Fabricate(:comment, user_id: user1.id, course_id: course8.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment73 = Fabricate(:comment, user_id: user1.id, course_id: course9.id, comment_text: "This course is awesome---the professor is excellent!")
comment74 = Fabricate(:comment, user_id: user2.id, course_id: course9.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment75 = Fabricate(:comment, user_id: user3.id, course_id: course9.id, comment_text: "Course went way too fast for me.")
comment76 = Fabricate(:comment, user_id: user4.id, course_id: course9.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment77 = Fabricate(:comment, user_id: user5.id, course_id: course9.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment78 = Fabricate(:comment, user_id: user6.id, course_id: course9.id, comment_text: "What a wonderful learning experience!")
comment79 = Fabricate(:comment, user_id: user7.id, course_id: course9.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment80 = Fabricate(:comment, user_id: user8.id, course_id: course9.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment81 = Fabricate(:comment, user_id: user1.id, course_id: course9.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment82 = Fabricate(:comment, user_id: user1.id, course_id: course10.id, comment_text: "This course is awesome---the professor is excellent!")
comment83 = Fabricate(:comment, user_id: user2.id, course_id: course10.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment84 = Fabricate(:comment, user_id: user3.id, course_id: course10.id, comment_text: "Course went way too fast for me.")
comment85 = Fabricate(:comment, user_id: user4.id, course_id: course10.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment86 = Fabricate(:comment, user_id: user5.id, course_id: course10.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment87 = Fabricate(:comment, user_id: user6.id, course_id: course10.id, comment_text: "What a wonderful learning experience!")
comment88 = Fabricate(:comment, user_id: user7.id, course_id: course10.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment89 = Fabricate(:comment, user_id: user8.id, course_id: course10.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment90 = Fabricate(:comment, user_id: user1.id, course_id: course10.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")

comment91 = Fabricate(:comment, user_id: user1.id, course_id: course11.id, comment_text: "This course is awesome---the professor is excellent!")
comment92 = Fabricate(:comment, user_id: user2.id, course_id: course11.id, comment_text: "I wish I had had such an awesome professor in college.  So great!")
comment93 = Fabricate(:comment, user_id: user3.id, course_id: course11.id, comment_text: "Course went way too fast for me.")
comment94 = Fabricate(:comment, user_id: user4.id, course_id: course11.id, comment_text: "Would have liked more support to go with the course. TAs would be a helpful addition.")
comment95 = Fabricate(:comment, user_id: user5.id, course_id: course11.id, comment_text: "Learned a lot in this course, though it is not for the faint of heart.  You must stay on top of the readings.  I would buy the book and read it beforehand.")
comment96 = Fabricate(:comment, user_id: user6.id, course_id: course11.id, comment_text: "What a wonderful learning experience!")
comment97 = Fabricate(:comment, user_id: user7.id, course_id: course11.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.")
comment98 = Fabricate(:comment, user_id: user8.id, course_id: course11.id, comment_text: "Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam.")
comment99 = Fabricate(:comment, user_id: user1.id, course_id: course11.id, comment_text: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut")
